// Hands generated bytes to the browser as a named download. No return value:
// the browser owns the save dialog and we cannot observe a cancel.

export function downloadBytes(bytes: Uint8Array | string, filename: string, mimeType: string): void {
  const part: BlobPart = typeof bytes === 'string' ? bytes : new Uint8Array(bytes);
  const blob = new Blob([part], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick so Safari has started the download.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
